# Generated by Django 3.2.8 on 2021-11-01 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('maths', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('physics', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('chemistry', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('computer_science', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('grade', models.CharField(default='A', max_length=1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
