# Generated by Django 3.2.8 on 2021-11-12 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_marksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
