# Generated by Django 3.2.8 on 2021-11-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_marksheet_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksheet',
            name='name',
            field=models.CharField(default='Unnamed', max_length=200),
        ),
    ]
